version: '3.7'

services:
  node0:
    container_name: node0
    image: tendermint/tendermint:v0.34.24
    command: ["node", "--proxy_app=kvstore"]
    cap_add:
      - NET_ADMIN
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26660"
    volumes:
      - ./node0:/tendermint
    networks:
      tendermintnet:
        ipv4_address: 172.30.0.2

  node1:
    container_name: node1
    image: tendermint/tendermint:v0.34.24
    command: ["node", "--proxy_app=kvstore"]
    cap_add:
      - NET_ADMIN
    ports:
      - "26666:26656"
      - "26667:26657"
      - "26668:26660"
    volumes:
      - ./node1:/tendermint
    networks:
      tendermintnet:
        ipv4_address: 172.30.0.3

  node2:
    container_name: node2
    image: tendermint/tendermint:v0.34.24
    command: ["node", "--proxy_app=kvstore"]
    cap_add:
      - NET_ADMIN
    ports:
      - "26676:26656"
      - "26677:26657"
      - "26678:26660"
    volumes:
      - ./node2:/tendermint
    networks:
      tendermintnet:
        ipv4_address: 172.30.0.4

  node3:
    container_name: node3
    image: tendermint/tendermint:v0.34.24
    command: ["node", "--proxy_app=kvstore"]
    cap_add:
      - NET_ADMIN
    ports:
      - "26686:26656"
      - "26687:26657"
      - "26688:26660"
    volumes:
      - ./node3:/tendermint
    networks:
      tendermintnet:
        ipv4_address: 172.30.0.5

  node4:
    container_name: node4
    image: tendermint/tendermint:v0.34.24
    command: ["node", "--proxy_app=kvstore"]
    cap_add:
      - NET_ADMIN
    ports:
      - "26696:26656"
      - "26697:26657"
      - "26698:26660"
    volumes:
      - ./node4:/tendermint
    networks:
      tendermintnet:
        ipv4_address: 172.30.0.6

  node5:
    container_name: node5
    image: tendermint/tendermint:v0.34.24
    command: ["node", "--proxy_app=kvstore"]
    cap_add:
      - NET_ADMIN
    ports:
      - "26706:26656"
      - "26707:26657"
      - "26708:26660"
    volumes:
      - ./node5:/tendermint
    networks:
      tendermintnet:
        ipv4_address: 172.30.0.7

  node6:
    container_name: node6
    image: tendermint/tendermint:v0.34.24
    command: ["node", "--proxy_app=kvstore"]
    cap_add:
      - NET_ADMIN
    ports:
      - "26716:26656"
      - "26717:26657"
      - "26718:26660"
    volumes:
      - ./node6:/tendermint
    networks:
      tendermintnet:
        ipv4_address: 172.30.0.8

  node7:
    container_name: node7
    image: tendermint/tendermint:v0.34.24
    command: ["node", "--proxy_app=kvstore"]
    cap_add:
      - NET_ADMIN
    ports:
      - "26726:26656"
      - "26727:26657"
      - "26728:26660"
    volumes:
      - ./node7:/tendermint
    networks:
      tendermintnet:
        ipv4_address: 172.30.0.9

networks:
  tendermintnet:
    external: true
